name: CI

on:
    schedule:
    - cron: "0 8 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Master
      uses: actions/checkout@v1
    - name: Configure AWS Cli
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region eu-west-2
    - name: Get Previous Stats
      run: aws s3 cp s3://icdss-members/members.json .
    - name: Calculate New Members
      run: python3 get_members.py ${{ secrets.UNION_API_KEY }} ${{ secrets.SLACK_CHANNEL_URL }}
    - name: Update s3
      run: aws s3 cp ./members.json s3://icdss-members/members.json
